const path = require('path')
module.exports = require("yargs")(process.argv.slice(2))
    .usage('Usage: $0 [options]')
    .example('$0 -u %USERNAME% -p xxx -s https://localhost:8443 -r master -o example/master.puml  -o example/master.png  -o example/master.svg', 'generate plantuml Keycloak realm representation')
    .alias('t', 'template')
    .nargs('t', 1)
    .describe('t', 'Template folder path')
    .default('t', path.join(__dirname, '../template'))
    .alias('l', 'legend')
    .nargs('l', 1)
    .describe('l', 'Display legend')
    .default('l', 'true')
    .alias('k', 'skipRoles')
    .nargs('k', 0)
    .describe('k', 'skip roles generation')
    .alias('f', 'filter')
    .nargs('f', 1)
    .describe('f', 'Filter with regexp (unsensitive to case) Keycloak object by name')
    .alias('n', 'note')
    .nargs('n', 0)
    .describe('n', 'Generate notes with description')
    .alias('o', 'output')
    .describe('o', 'path of plantuml export (puml|png|svg`) or empty to display puml')
    .alias('u', 'user')
    .nargs('u', 1)
    .describe('u', 'Keycloak user')
    .demandOption(['u'])
    .alias('p', 'password')
    .nargs('p', 1)
    .describe('p', 'Keycloak user\'s password')
    .demandOption(['p'])
    .alias('s', 'server')
    .nargs('s', 1)
    .describe('s', 'Keycloak server name')
    .demandOption(['s'])
    .alias('r', 'realm')
    .nargs('r', 1)
    .describe('r', 'Keycloak realm name to represent')
    .default('r', 'master')
    .help('h')
    .alias('h', 'help')
    .completion()
    .argv